# Generated by Django 4.0.4 on 2022-04-27 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import membership.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('membership_validity_in_months', models.IntegerField(default=1)),
                ('membership_tier', models.CharField(max_length=128)),
                ('features', models.JSONField(default=membership.models.get_default_features_list)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipSubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_datetime', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
