# Generated by Django 4.0.4 on 2022-04-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Service Category Name')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_alt_text', models.TextField(verbose_name='Image alt. text')),
                ('image', models.ImageField(upload_to='images/service_images/secondary_images/', verbose_name='Service Image')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/service_images/main_images/', verbose_name='Main Image')),
                ('main_image_link', models.URLField(blank=True, null=True, verbose_name='Main Image Link')),
                ('main_image_alt_text', models.TextField(blank=True, default='Service Main Image', verbose_name='Main Image alt. text')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('categories', models.ManyToManyField(to='service.servicecategory', verbose_name='Categories')),
                ('secondary_images', models.ManyToManyField(blank=True, to='service.serviceimage', verbose_name='Secondary Images')),
            ],
        ),
    ]
