# Generated by Django 4.0.4 on 2022-04-27 07:16

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('ESEWA', 'Esewa'), ('KHALTI', 'Khalti')], max_length=32, verbose_name='Payment Method')),
                ('reference', models.CharField(default=payment.models.get_payment_reference_token, max_length=32, verbose_name='Payment Reference')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('paid_amount', models.FloatField(blank=True, null=True, verbose_name='Amount Paid')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
            ],
        ),
    ]
